#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

output="tmp/onboarding/proof-vscode-mcp.json"
human_output="tmp/onboarding/proof-vscode.out"
startup_output=".github/instructions/amai-continuity-startup.instructions.md"
startup_contract=".amai/onboarding/project-chat-startup-contract.json"
rm -f "${output}" "${human_output}" "${startup_output}" "${startup_contract}"

./scripts/onboard_local.sh --client vscode --yes --output "${output}" >"${human_output}"

test -f .env
test -f "${output}"
test -f "${human_output}"
test -f "${startup_output}"
test -f "${startup_contract}"
grep -q '"servers"' "${output}"
grep -q 'run_mcp_stdio.sh' "${output}"
grep -q '"artifact_version": "workspace-startup-contract-v1"' "${startup_contract}"
grep -q '"startup_contract_sha256": "' "${startup_contract}"
grep -q '"workspace_contract_relative_path": ".amai/onboarding/project-chat-startup-contract.json"' "${startup_contract}"
grep -q '"missing_or_unreadable_fail_closed": true' "${startup_contract}"
grep -q '"sha256_mismatch_fail_closed": true' "${startup_contract}"
grep -q '"required_action_kind_when_resume_required": "resume_required_return_task"' "${startup_contract}"
grep -q '".amai/continuity/project-chat-startup-state.json"' "${startup_contract}"
grep -q '"startup_execution_gate_field": "startup_execution_gate"' "${startup_contract}"
grep -q '"command": "continuity startup-state"' "${startup_contract}"
grep -q '"startup_execution_gate"' "${startup_contract}"
grep -q '"project_task_tree"' "${startup_contract}"
grep -q '"project_task_ledger"' "${startup_contract}"
grep -q 'amai_continuity_startup' "${startup_output}"
grep -q '.amai/onboarding/project-chat-startup-contract.json' "${startup_output}"
grep -q 'startup_contract_sha256 = "' "${startup_output}"
grep -q 'workspace_contract_required_before_tool_call = true' "${startup_output}"
grep -q 'missing_or_unreadable_fail_closed = true' "${startup_output}"
grep -q 'sha256_mismatch_fail_closed = true' "${startup_output}"
grep -q '.amai/continuity/project-chat-startup-state.json' "${startup_output}"
grep -q 'startup_execution_gate' "${startup_output}"
grep -q 'continuity startup-state --repo-root' "${startup_output}"
grep -q 'execctl_resume_contract_summary' "${startup_output}"
grep -q 'execctl_resume_obligation' "${startup_output}"
grep -q 'startup_next_action' "${startup_output}"
grep -q 'execctl_active_lease' "${startup_output}"
grep -q 'lease_owner_state' "${startup_output}"
grep -q 'execctl_active_lease_summary' "${startup_output}"
grep -q 'previous_session_owner' "${startup_output}"
grep -q 'resume_required_return_task' "${startup_output}"
grep -q 'required_return_task' "${startup_output}"
grep -q 'project_task_tree' "${startup_output}"
grep -q 'project_task_ledger' "${startup_output}"
grep -q 'Auto-start readiness: instruction-backed' "${human_output}"
grep -q 'Machine-readable startup contract:' "${human_output}"
grep -q 'Где лежит startup contract JSON:' "${human_output}"
grep -q 'Startup contract SHA-256:' "${human_output}"
grep -q 'Почему такой режим:' "${human_output}"
grep -q 'Что машина реально показала после установки:' "${human_output}"

cargo run --quiet -- status >/dev/null

echo "proof_onboarding: ok"
